server:
  port: 9080

spring:
  application:
    name: hr-service

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 10000
        requestVolumeThreshold: 5
  dashboard:
    proxy-stream-allow-list: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"


